### PR TITLE
passing data_level arg and dummy test

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
It's not completely solving the issue yet, I get this error now:

```
Traceback (most recent call last):
  File "/home/gabriele/Workspace/dispatcher-app/cdci_data_analysis/analysis/queries.py", line 604, in get_query_products
    self.query_prod_list = self.get_dummy_products(instrument,
  File "/home/gabriele/Workspace/dispatcher-app/venv39/lib/python3.9/site-packages/dispatcher_plugin_integral_all_sky/spiacs_lightcurve_query.py", line 460, in get_dummy_products
    prod_list = SpicasLightCurve.build_from_res(res,
  File "/home/gabriele/Workspace/dispatcher-app/venv39/lib/python3.9/site-packages/dispatcher_plugin_integral_all_sky/spiacs_lightcurve_query.py", line 214, in build_from_res
    raise SpiacsAnalysisException(
dispatcher_plugin_integral_all_sky.spiacs_dataserver_dispatcher.SpiacsAnalysisException: spiacs light curve failed: AssertionError()
```

since I am using an empty `query_spiacs_lc.txt` file. 

Where can I find a working one?

**Comment by burnout87** [comment]
image

**Review by dsavchenko — APPROVED** [review]
Why did it stop working so this adaptation needed?

**Comment by burnout87** [comment]
> Why did it stop working so this adaptation needed?

it was probably made only for Real products, but not for dummy ones...just a guess

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
